// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class WrongidpasswordTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void wrongidpassword() {
    driver.get("https://www.konga.com/");
    driver.manage().window().setSize(new Dimension(1382, 744));
    {
      WebElement element = driver.findElement(By.cssSelector("div > a > picture > .lazyloading"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.linkText("Login / Signup")).click();
    driver.findElement(By.id("username")).click();
    driver.findElement(By.id("username")).sendKeys("ami");
    driver.findElement(By.id("username")).sendKeys("aminat@yahoo.com");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("oloooodoo");
    driver.findElement(By.cssSelector(".\\_988cf_1aDdJ")).click();
    driver.findElement(By.cssSelector(".\\_9a1ab_k0UMi:nth-child(3)")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".\\_9a1ab_k0UMi:nth-child(3)"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector(".\\_9a1ab_k0UMi:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".\\_9a1ab_k0UMi:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".\\_9a1ab_k0UMi:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".\\_9a1ab_k0UMi:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".\\_9a1ab_k0UMi:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".\\_9a1ab_k0UMi:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".\\_9a1ab_k0UMi:nth-child(3)")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".\\_9a1ab_k0UMi:nth-child(3)"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector(".\\_9a1ab_k0UMi:nth-child(3)")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".\\_9a1ab_k0UMi:nth-child(3)"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector(".\\_9a1ab_k0UMi:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".\\_9a1ab_k0UMi:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".\\_9a1ab_k0UMi:nth-child(3)")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".\\_9a1ab_k0UMi:nth-child(3)"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector(".\\_9a1ab_k0UMi:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".\\_9a1ab_k0UMi:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".\\_9a1ab_k0UMi:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".\\_9a1ab_k0UMi:nth-child(3)")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".\\_9a1ab_k0UMi:nth-child(3)"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector(".\\_9a1ab_k0UMi:nth-child(3)")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".\\_9a1ab_k0UMi:nth-child(3)"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector(".\\_9a1ab_k0UMi:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".\\_9a1ab_k0UMi:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".\\_9a1ab_k0UMi:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".\\_9a1ab_k0UMi:nth-child(3)")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".\\_9a1ab_k0UMi:nth-child(3)"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector(".\\_9a1ab_k0UMi:nth-child(3)")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".\\_9a1ab_k0UMi:nth-child(3)"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector(".\\_9a1ab_k0UMi:nth-child(3)")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".\\_9a1ab_k0UMi:nth-child(3)"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector(".\\_9a1ab_k0UMi:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".\\_9a1ab_k0UMi:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".\\_9a1ab_k0UMi:nth-child(3)")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".\\_9a1ab_k0UMi:nth-child(3)"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector(".\\_9a1ab_k0UMi:nth-child(3)")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".\\_9a1ab_k0UMi:nth-child(3)"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector(".\\_9a1ab_k0UMi:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".\\_9a1ab_k0UMi:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".\\_9a1ab_k0UMi:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".\\_9a1ab_k0UMi:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".\\_9a1ab_k0UMi:nth-child(3)")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".\\_9a1ab_k0UMi:nth-child(3)"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector(".\\_9a1ab_k0UMi:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".\\_9a1ab_k0UMi:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".\\_9a1ab_k0UMi:nth-child(3)")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".\\_9a1ab_k0UMi:nth-child(3)"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector(".\\_9a1ab_k0UMi:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".\\_9a1ab_k0UMi:nth-child(3)")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".\\_9a1ab_k0UMi:nth-child(3)"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector(".\\_9a1ab_k0UMi:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".\\_9a1ab_k0UMi:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".\\_9a1ab_k0UMi:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".\\_9a1ab_k0UMi:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".\\_9a1ab_k0UMi:nth-child(3)")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".\\_9a1ab_k0UMi:nth-child(3)"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector(".\\_9a1ab_k0UMi:nth-child(3)")).click();
    assertThat(driver.findElement(By.cssSelector(".\\_9a1ab_k0UMi:nth-child(3)")).getText(), is("The username or password you have entered is incorrect. Please try again."));
    driver.findElement(By.cssSelector(".\\_40e43_1f83p > span")).click();
    driver.close();
  }
}
